### ISSUE TITLE
"Error: $interpolate:noconcatMultiple Expressions"

### ISSUE THREAD

**Issue by adrianxadamn** [adrianxadamn/join_me#1]
I'm getting an "Error: $interpolate:noconcatMultiple Expressions" on my app whenever I try to bind data from my services to the html.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/{{vm.chatroomService.retrieve().video}}" frameborder="0" allowfullscreen></iframe>`

**Comment by ghost** [comment]
This is not a good issue. Please resubmit after following the [protocol for writing a good issue](https://github.com/ga-students/WDI_DTLA_8/tree/master/projects/project_issues_protocol).
